//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecyclingBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FractionInfoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FractionInfoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecyclingBot.Properties.FractionInfoResources", typeof(FractionInfoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Recycle It?
        ///
        ///Look for curbside, school, or work recycling bins or find a local recycling drop-off center — and be sure to check local recycling ordinances. In some states, beverage containers have a deposit refund and can be returned to the store where they were purchased. 
        ///
        ///Many recycling centers ask that you give food containers a quick rinse, remove all non-glass parts and sort the glass by color. .
        /// </summary>
        internal static string GlassFractionInfo_HowToRecycle {
            get {
                return ResourceManager.GetString("GlassFractionInfo_HowToRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass.
        /// </summary>
        internal static string GlassFractionInfo_Topic {
            get {
                return ResourceManager.GetString("GlassFractionInfo_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Types Of Glass I Can Recycle?
        ///
        ///Glass can be produced with a variety of formulas and processes for different purposes. The glass used in food packaging is generally soda-lime glass, but kitchenware, for example, can be made with borosilicate for use with extreme temperature changes. Likewise, window glass is produced differently for durability. Unfortunately, these kinds of glass all have different melting points and contain additional components, meaning they can’t usually be processed for recycling  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GlassFractionInfo_WhatCanBeRecycled {
            get {
                return ResourceManager.GetString("GlassFractionInfo_WhatCanBeRecycled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Collect?
        ///
        ///Glass Recycling Is Good for the Environment
        ///A glass bottle that is sent to a landfill can take up to a million years to break down. By contrast, it takes as little as 30 days for a recycled glass bottle to leave your kitchen recycling bin and appear on a store shelf as a new glass container.
        ///
        ///Glass Recycling is Sustainable
        ///Glass containers are 100-percent recyclable, which means they can be recycled repeatedly, again and again, with no loss of purity or quality in the glass.
        ///
        ///Glass Rec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GlassFractionInfo_WhyCollect {
            get {
                return ResourceManager.GetString("GlassFractionInfo_WhyCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Recycle Incandescent Light Bulbs
        ///Incandescent light bulbs usually don’t contain any hazardous chemicals. Because of this, they are pretty easy to recycle. Simply place your burnt out light bulbs in the recycling bin or drop off at the nearest recycling center. If broken, please wrap in some sort of padding for safety.
        ///
        ///How To Recycle Halogen Light Bulbs
        ///Commonly used as outdoor flood lights, halogen bulbs are more advanced than regular incandescents. While they are more efficient, they burn at a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LampFractionInfo_HowToRecycle {
            get {
                return ResourceManager.GetString("LampFractionInfo_HowToRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamps.
        /// </summary>
        internal static string LampFractionInfo_Topic {
            get {
                return ResourceManager.GetString("LampFractionInfo_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Requirements
        ///Many states require lamp recycling and proper disposal of ballasts, batteries, and electronic waste by law. Make sure you are compliant with your state regulations.
        ///
        ///The Environment
        ///Fluorescent lamps contain mercury, and ballasts, batteries, and electronic waste can contain mercury, lead, metals, and other materials which have a harmful effect on the environment if not recycled.
        ///
        ///Recycling is Cost Effective
        ///Over the lifecycle of a fluorescent lamp, the cost to recycle is less than  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LampFractionInfo_WhyCollect {
            get {
                return ResourceManager.GetString("LampFractionInfo_WhyCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With scrap metal, the general rule is a product needs to be at least 50 percent metal. Even if that metal is surrounded by other materials like plastic, it’s worth recycling if it’s made mostly out of metal.
        ///
        ///If you have products with only a small amount of metal but it’s easy to remove, separate the metal. For example, a plastic three-ring binder is not scrap metal, but remove the metal rings and now you’re talking.
        ///
        ///Scrap metal is classified as either ferrous (containing iron, such as steel) and nonfe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetalFractionInfo_HowToRecycle {
            get {
                return ResourceManager.GetString("MetalFractionInfo_HowToRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        internal static string MetalFractionInfo_Topic {
            get {
                return ResourceManager.GetString("MetalFractionInfo_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap Reuse
        ///By definition, mining metal ores and refining them into usable metals is unsustainable; the amount of metals present on earth is fixed when considering (at least when considering any useful geological time scale). However, metals are easily recycled and reused, providing renewed opportunities for their use without having to mine and refine more of it. Thus, issues associated with mining like can be avoided, like acid mine drainage. By recycling, we reduce the need to manage extensive and potent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MetalFractionInfo_WhyCollect {
            get {
                return ResourceManager.GetString("MetalFractionInfo_WhyCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid getting paper wet, as this significantly reduces the recycling market. If your curbside program accepts all materials in the same bin/cart, empty your containers before tossing them in so they don’t drain on your paper. If there’s rain in the forecast, wait until the morning of collection to put your bin at the curb.
        ///
        ///If possible, use a black marker to remove sensitive information instead of shredding paper. Ink is easily removed in the recycling process, but shredding paper reduces the fiber length [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PaperFractionInfo_HowToRecycle {
            get {
                return ResourceManager.GetString("PaperFractionInfo_HowToRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper.
        /// </summary>
        internal static string PaperFractionInfo_Topic {
            get {
                return ResourceManager.GetString("PaperFractionInfo_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incineration Reduction
        ///Besides saving landfill space, when people recycle paper, there&apos;s reduced need for trash incineration. Some municipalities burn trash rather than storing it in landfills. By diverting paper out of the trash stream, there is less to burn, so there&apos;s less need for incinerators and less ash output and air pollution.
        ///
        ///Energy Conservation
        ///Manufacturing paper from recycled paper fiber requires less energy than making paper from virgin wood pulp. In fact, making recycled paper is estimat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PaperFractionInfo_WhyCollect {
            get {
                return ResourceManager.GetString("PaperFractionInfo_WhyCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycling by the Numbers 
        ///The symbol code we are familiar with — digits ranging from 1 to 7 surrounded by a triangle of arrows — was designed by The Society of the Plastics Industry (SPI) in 1988 to allow consumers and recyclers to differentiate types of plastics while providing a uniform coding system for manufacturers.
        ///
        ///PET
        ///The easiest and most common plastics to recycle are made of polyethylene terephthalate (PET) and are assigned the number 1. Examples include soda and water bottles, medicine contai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlasticFractionInfo_HowToRecycle {
            get {
                return ResourceManager.GetString("PlasticFractionInfo_HowToRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic.
        /// </summary>
        internal static string PlasticFractionInfo_Topic {
            get {
                return ResourceManager.GetString("PlasticFractionInfo_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic Use Is Growing
        ///As the use of plastics has increased over the years, they have become a larger part of our nation&apos;s municipal solid waste (MSW)—growing from less than 1% in 1960 to more than 13% in 2013, according to a report by the Environmental Protection Agency.
        ///
        ///It Conserves Natural Resources and Energy
        ///Recycling plastics reduces the amount of energy and resources (such as water, petroleum, natural gas, and coal) needed to create plastic. According to a 2009 study by researchers Peter Gleick  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlasticFractionInfo_WhyCollect {
            get {
                return ResourceManager.GetString("PlasticFractionInfo_WhyCollect", resourceCulture);
            }
        }
    }
}
