//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecyclingBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecyclingCodeInfoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecyclingCodeInfoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecyclingBot.Properties.RecyclingCodeInfoResources", typeof(RecyclingCodeInfoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other plastics, such as acrylic, nylon, polycarbonate, and polylactic acid (a bioplastic also known as PLA), and multilayer combinations of different plastics..
        /// </summary>
        internal static string OtherRecyclingCode_About {
            get {
                return ResourceManager.GetString("OtherRecyclingCode_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER or O.
        /// </summary>
        internal static string OtherRecyclingCode_Name {
            get {
                return ResourceManager.GetString("OtherRecyclingCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 7 plastics have traditionally not been recycled, though some curbside programs now take them..
        /// </summary>
        internal static string OtherRecyclingCode_RecyclingInfo {
            get {
                return ResourceManager.GetString("OtherRecyclingCode_RecyclingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottles, plastic lumber applications, headlight lenses, and safety shields/glasses..
        /// </summary>
        internal static string OtherRecyclingCode_Uses {
            get {
                return ResourceManager.GetString("OtherRecyclingCode_Uses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-density polyethylene (HDPE) or polyethylene high-density (PEHD) is a thermoplastic polymer produced from the monomer ethylene. It is sometimes called &quot;alkathene&quot; or &quot;polythene&quot; when used for HDPE pipes. With a high strength-to-density ratio, HDPE is used in the production of plastic bottles, corrosion-resistant piping, geomembranes and plastic lumber. HDPE is commonly recycled, and has the number &quot;2&quot; as its resin identification code..
        /// </summary>
        internal static string PE_HDRecyclingCode_About {
            get {
                return ResourceManager.GetString("PE_HDRecyclingCode_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDPE.
        /// </summary>
        internal static string PE_HDRecyclingCode_Name {
            get {
                return ResourceManager.GetString("PE_HDRecyclingCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked up through most curbside recycling programs, although some allow only those containers with necks..
        /// </summary>
        internal static string PE_HDRecyclingCode_RecyclingInfo {
            get {
                return ResourceManager.GetString("PE_HDRecyclingCode_RecyclingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottles, grocery bags, milk jugs, recycling bins, agricultural pipe, base cups, car stops, playground equipment, and plastic lumber..
        /// </summary>
        internal static string PE_HDRecyclingCode_Uses {
            get {
                return ResourceManager.GetString("PE_HDRecyclingCode_Uses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low-density polyethylene (LDPE) is a thermoplastic made from the monomer ethylene. It was the first grade of polyethylene, produced in 1933 by Imperial Chemical Industries (ICI) using a high pressure process via free radical polymerization. Its manufacture employs the same method today. The EPA estimates 5.7% of LDPE (recycling number 4) is recycled in the United States. Despite competition from more modern polymers, LDPE continues to be an important plastic grade. In 2013 the worldwide LDPE market reached  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PE_LDRecyclingCode_About {
            get {
                return ResourceManager.GetString("PE_LDRecyclingCode_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDPE or PE-LD.
        /// </summary>
        internal static string PE_LDRecyclingCode_Name {
            get {
                return ResourceManager.GetString("PE_LDRecyclingCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDPE is not often recycled through curbside programs, but some communities will accept it. Plastic shopping and clothes dry cleaning bags can be returned to many stores for recycling..
        /// </summary>
        internal static string PE_LDRecyclingCode_RecyclingInfo {
            get {
                return ResourceManager.GetString("PE_LDRecyclingCode_RecyclingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic bags, six pack rings, various containers, dispensing bottles, wash bottles, tubing, and various molded laboratory equipment..
        /// </summary>
        internal static string PE_LDRecyclingCode_Uses {
            get {
                return ResourceManager.GetString("PE_LDRecyclingCode_Uses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyethylene terephthalate (sometimes written poly(ethylene terephthalate)), commonly abbreviated PET, PETE, or the obsolete PETP or PET-P, is the most common thermoplastic polymer resin of the polyester family and is used in fibres for clothing, containers for liquids and foods, thermoforming for manufacturing, and in combination with glass fibre for engineering resins..
        /// </summary>
        internal static string PETRecyclingCode_About {
            get {
                return ResourceManager.GetString("PETRecyclingCode_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PET or PETE.
        /// </summary>
        internal static string PETRecyclingCode_Name {
            get {
                return ResourceManager.GetString("PETRecyclingCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked up through most curbside recycling programs..
        /// </summary>
        internal static string PETRecyclingCode_RecyclingInfo {
            get {
                return ResourceManager.GetString("PETRecyclingCode_RecyclingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyester fibres (Polar Fleece), thermoformed sheet, strapping, soft drink bottles, tote bags, furniture, carpet, paneling and (occasionally) new containers..
        /// </summary>
        internal static string PETRecyclingCode_Uses {
            get {
                return ResourceManager.GetString("PETRecyclingCode_Uses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polypropylene belongs to the group of polyolefins and is partially crystalline and non-polar. Its properties are similar to polyethylene, but it is slightly harder and more heat resistant. It is a white, mechanically rugged material and has a high chemical resistance. Polypropylene is the second-most widely produced commodity plastic (after polyethylene) and it is often used in packaging and labeling. In 2019, the global market for polypropylene was worth $126.03 billion..
        /// </summary>
        internal static string PPRecyclingCode_About {
            get {
                return ResourceManager.GetString("PPRecyclingCode_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP.
        /// </summary>
        internal static string PPRecyclingCode_Name {
            get {
                return ResourceManager.GetString("PPRecyclingCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 5 plastics can be recycled through some curbside programs..
        /// </summary>
        internal static string PPRecyclingCode_RecyclingInfo {
            get {
                return ResourceManager.GetString("PPRecyclingCode_RecyclingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto parts, industrial fibres, food containers, and dishware..
        /// </summary>
        internal static string PPRecyclingCode_Uses {
            get {
                return ResourceManager.GetString("PPRecyclingCode_Uses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polystyrene (PS) is a synthetic aromatic hydrocarbon polymer made from the monomer known as styrene. Polystyrene can be solid or foamed. General-purpose polystyrene is clear, hard, and rather brittle. It is an inexpensive resin per unit weight. It is a rather poor barrier to oxygen and water vapour and has a relatively low melting point. Polystyrene is one of the most widely used plastics, the scale of its production being several million tonnes per year. Polystyrene can be naturally transparent, but can be [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PSRecyclingCode_About {
            get {
                return ResourceManager.GetString("PSRecyclingCode_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS.
        /// </summary>
        internal static string PSRecyclingCode_Name {
            get {
                return ResourceManager.GetString("PSRecyclingCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 6 plastics can be recycled through some curbside programs..
        /// </summary>
        internal static string PSRecyclingCode_RecyclingInfo {
            get {
                return ResourceManager.GetString("PSRecyclingCode_RecyclingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desk accessories, cafeteria trays, plastic utensils, coffee cup lids, toys, video cassettes and cases, clamshell containers, packaging peanuts, and insulation board and other expanded polystyrene products (e.g., Styrofoam)..
        /// </summary>
        internal static string PSRecyclingCode_Uses {
            get {
                return ResourceManager.GetString("PSRecyclingCode_Uses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVC comes in two basic forms: rigid (sometimes abbreviated as RPVC) and flexible. The rigid form of PVC is used in construction for pipe and in profile applications such as doors and windows. It is also used in making bottles, non-food packaging, food-covering sheets, and cards (such as bank or membership cards). It can be made softer and more flexible by the addition of plasticizers, the most widely used being phthalates. In this form, it is also used in plumbing, electrical cable insulation, imitation lea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PVCRecyclingCode_About {
            get {
                return ResourceManager.GetString("PVCRecyclingCode_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVC or V.
        /// </summary>
        internal static string PVCRecyclingCode_Name {
            get {
                return ResourceManager.GetString("PVCRecyclingCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycled 740,000 tonnes in 2018 through Vinyl 2010 and VinylPlus initiatives..
        /// </summary>
        internal static string PVCRecyclingCode_RecyclingInfo {
            get {
                return ResourceManager.GetString("PVCRecyclingCode_RecyclingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe, window profile, siding, fencing, flooring, shower curtains, lawn chairs, non-food bottles, and children&apos;s toys..
        /// </summary>
        internal static string PVCRecyclingCode_Uses {
            get {
                return ResourceManager.GetString("PVCRecyclingCode_Uses", resourceCulture);
            }
        }
    }
}
